"""add analytics tables

Revision ID: 98ed1e32bf23
Revises: 5151f4ec6575
Create Date: 2026-04-18 16:28:48.571216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '98ed1e32bf23'
down_revision: Union[str, Sequence[str], None] = '5151f4ec6575'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('lower_tier_lift_rate', sa.Float(), nullable=True),
    sa.Column('common_error_index', sa.Float(), nullable=True),
    sa.Column('mid_tier_difficulty_tolerance', sa.Float(), nullable=True),
    sa.Column('learning_path_convergence', sa.Float(), nullable=True),
    sa.Column('ability_distribution_shift', sa.Float(), nullable=True),
    sa.Column('collaboration_activity', sa.Float(), nullable=True),
    sa.Column('kg_connectivity', sa.Float(), nullable=True),
    sa.Column('bottleneck_duration_days', sa.Float(), nullable=True),
    sa.Column('feedback_adoption_tendency', sa.JSON(), nullable=True),
    sa.Column('task_completion_resilience', sa.Float(), nullable=True),
    sa.Column('raw_snapshot', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'snapshot_date', name='uq_class_daily_snapshot')
    )
    op.create_index(op.f('ix_class_daily_snapshots_class_id'), 'class_daily_snapshots', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_daily_snapshots_snapshot_date'), 'class_daily_snapshots', ['snapshot_date'], unique=False)
    op.create_table('intervention_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('agent_type', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('suggestion', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('priority', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_tasks_class_id'), 'intervention_tasks', ['class_id'], unique=False)
    op.create_index(op.f('ix_intervention_tasks_student_id'), 'intervention_tasks', ['student_id'], unique=False)
    op.create_table('student_daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('summary_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('vocab_growth_rate', sa.Float(), nullable=True),
    sa.Column('sm2_retention_rate', sa.Float(), nullable=True),
    sa.Column('active_lookup_conversion', sa.Float(), nullable=True),
    sa.Column('morph_transfer_ability', sa.Float(), nullable=True),
    sa.Column('long_term_memory_robustness', sa.Integer(), nullable=True),
    sa.Column('grammar_error_decay_slope', sa.Float(), nullable=True),
    sa.Column('advanced_vocab_substitution', sa.Float(), nullable=True),
    sa.Column('msl_diversity_index', sa.Float(), nullable=True),
    sa.Column('logical_coherence_trend', sa.Float(), nullable=True),
    sa.Column('semantic_accuracy_trend', sa.Float(), nullable=True),
    sa.Column('response_latency_avg_ms', sa.Integer(), nullable=True),
    sa.Column('speech_wpm', sa.Float(), nullable=True),
    sa.Column('difficulty_jump_success', sa.Float(), nullable=True),
    sa.Column('cross_cultural_deviation', sa.Float(), nullable=True),
    sa.Column('paraphrase_count', sa.Integer(), nullable=True),
    sa.Column('learning_stability_std', sa.Float(), nullable=True),
    sa.Column('error_regression_rate', sa.Float(), nullable=True),
    sa.Column('feedback_response_depth', sa.Float(), nullable=True),
    sa.Column('topic_coverage_breadth', sa.Integer(), nullable=True),
    sa.Column('autonomous_drive_count', sa.Integer(), nullable=True),
    sa.Column('raw_snapshot', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'summary_date', name='uq_student_daily_summary')
    )
    op.create_index(op.f('ix_student_daily_summaries_summary_date'), 'student_daily_summaries', ['summary_date'], unique=False)
    op.create_index(op.f('ix_student_daily_summaries_user_id'), 'student_daily_summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_daily_summaries_user_id'), table_name='student_daily_summaries')
    op.drop_index(op.f('ix_student_daily_summaries_summary_date'), table_name='student_daily_summaries')
    op.drop_table('student_daily_summaries')
    op.drop_index(op.f('ix_intervention_tasks_student_id'), table_name='intervention_tasks')
    op.drop_index(op.f('ix_intervention_tasks_class_id'), table_name='intervention_tasks')
    op.drop_table('intervention_tasks')
    op.drop_index(op.f('ix_class_daily_snapshots_snapshot_date'), table_name='class_daily_snapshots')
    op.drop_index(op.f('ix_class_daily_snapshots_class_id'), table_name='class_daily_snapshots')
    op.drop_table('class_daily_snapshots')
    # ### end Alembic commands ###
