"""Analytics domain models for teacher analytics module.

Defines SQLModel tables for:
- StudentDailySummary: per-student daily longitudinal metrics (20 dimensions)
- ClassDailySnapshot: per-class daily horizontal metrics (10 dimensions)
- InterventionTask: actionable intervention tasks generated by tiered agents
"""

from __future__ import annotations

import datetime as _dt
from typing import Any

from sqlalchemy import Column, UniqueConstraint
from sqlalchemy.types import JSON
from sqlmodel import Field, SQLModel


class StudentDailySummary(SQLModel, table=True):
    """学生每日纵向摘要 — 覆盖 20 个评价维度。"""

    __tablename__ = "student_daily_summaries"
    __table_args__ = (UniqueConstraint("user_id", "summary_date", name="uq_student_daily_summary"),)

    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    class_id: str | None = Field(default=None, index=True, max_length=64)
    summary_date: _dt.date = Field(index=True)
    created_at: _dt.datetime = Field(default_factory=_dt.datetime.utcnow)

    # ── A1. 词汇学习维度 ──
    vocab_growth_rate: float | None = Field(default=None, description="A1 词汇熟练度增长率")
    sm2_retention_rate: float | None = Field(default=None, description="A2 SM-2 复习遗忘抑制比")
    active_lookup_conversion: float | None = Field(default=None, description="A3 主动查词转化率")
    morph_transfer_ability: float | None = Field(default=None, description="A4 构词法迁移能力")
    long_term_memory_robustness: int | None = Field(default=None, description="A5 长时记忆健壮度")

    # ── A2. 作文能力维度 ──
    grammar_error_decay_slope: float | None = Field(default=None, description="A6 语法错误收敛速度")
    advanced_vocab_substitution: float | None = Field(default=None, description="A7 高级词汇替代率")
    msl_diversity_index: float | None = Field(default=None, description="A8 句式多样性指数 (MSL)")
    logical_coherence_trend: float | None = Field(default=None, description="A9 逻辑衔接连贯度")
    semantic_accuracy_trend: float | None = Field(default=None, description="A10 语义表达准确性")

    # ── A3. 口语对话维度 ──
    response_latency_avg_ms: int | None = Field(default=None, description="A11 对话响应潜伏期 (ms)")
    speech_wpm: float | None = Field(default=None, description="A12 语音产出速率 (WPM)")
    difficulty_jump_success: float | None = Field(default=None, description="A13 对话难度跳变成功率")
    cross_cultural_deviation: float | None = Field(default=None, description="A14 跨文化得体性偏离值")
    paraphrase_count: int | None = Field(default=None, description="A15 口语解释/转述能力")

    # ── A4. 综合学习倾向维度 ──
    learning_stability_std: float | None = Field(default=None, description="A16 学习行为稳定性")
    error_regression_rate: float | None = Field(default=None, description="A17 错误复发率")
    feedback_response_depth: float | None = Field(default=None, description="A18 反馈响应深度")
    topic_coverage_breadth: int | None = Field(default=None, description="A19 主题覆盖广度")
    autonomous_drive_count: int | None = Field(default=None, description="A20 自主学习驱动力")

    # ── 用户画像融合字段 ──
    level: str | None = Field(default=None, max_length=32, description="学生英语水平（来自StudentProfile）")
    goals: list[str] = Field(default_factory=list, sa_column=Column(JSON), description="学习目标（来自StudentProfile）")
    interests: list[str] = Field(default_factory=list, sa_column=Column(JSON), description="兴趣爱好（来自StudentProfile）")
    llm_narrative: str | None = Field(default=None, description="LLM生成的个性化分析摘要")
    profile_snapshot: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON), description="画像+LLM分析的完整快照")

    # 预留：原始数据快照（便于回溯与调试）
    raw_snapshot: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))


class StudentLongitudinalSummary(SQLModel, table=True):
    """学生窗口级纵向总结。

    保存可直接展示给教师的 LLM 总结，同时保留客观趋势、风险、证据片段，
    作为后续 Agent 和周报的共同输入。
    """

    __tablename__ = "student_longitudinal_summaries"
    __table_args__ = (
        UniqueConstraint(
            "user_id",
            "class_id",
            "window_start",
            "window_end",
            "window_days",
            name="uq_student_longitudinal_summary_window",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    class_id: str | None = Field(default=None, index=True, max_length=64)
    window_start: _dt.date = Field(index=True)
    window_end: _dt.date = Field(index=True)
    window_days: int = Field(default=14)
    summary_kind: str = Field(default="rolling_window", max_length=32)
    llm_summary: str = Field(default="")
    risk_flags: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    strength_flags: list[str] = Field(default_factory=list, sa_column=Column(JSON))
    metric_deltas: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    evidence: list[dict[str, Any]] = Field(default_factory=list, sa_column=Column(JSON))
    source_summary_ids: list[int] = Field(default_factory=list, sa_column=Column(JSON))
    meta_data: dict[str, Any] = Field(default_factory=dict, sa_column=Column("metadata", JSON))
    created_at: _dt.datetime = Field(default_factory=_dt.datetime.utcnow)
    updated_at: _dt.datetime = Field(default_factory=_dt.datetime.utcnow)


class ClassDailySnapshot(SQLModel, table=True):
    """班级每日横向快照 — 覆盖 10 个评价维度。"""

    __tablename__ = "class_daily_snapshots"
    __table_args__ = (UniqueConstraint("class_id", "snapshot_date", name="uq_class_daily_snapshot"),)

    id: int | None = Field(default=None, primary_key=True)
    class_id: str = Field(index=True, max_length=64)
    snapshot_date: _dt.date = Field(index=True)
    created_at: _dt.datetime = Field(default_factory=_dt.datetime.utcnow)

    # ── B. 班级中下到中上层趋势维度 ──
    lower_tier_lift_rate: float | None = Field(default=None, description="B1 中下层进步斜率")
    common_error_index: float | None = Field(default=None, description="B2 群体性错误共性指数")
    mid_tier_difficulty_tolerance: float | None = Field(default=None, description="B3 中层学生难度耐受力")
    learning_path_convergence: float | None = Field(default=None, description="B4 学习路径收敛度")
    ability_distribution_shift: float | None = Field(default=None, description="B5 能力等级分布位移")
    collaboration_activity: float | None = Field(default=None, description="B6 协作/竞争活跃度")
    kg_connectivity: float | None = Field(default=None, description="B7 知识图谱连通性")
    bottleneck_duration_days: float | None = Field(default=None, description="B8 中上层瓶颈期时长")
    feedback_adoption_tendency: dict[str, Any] = Field(
        default_factory=dict,
        sa_column=Column(JSON),
        description="B9 反馈采纳群体倾向 (结构建议比例, 语法建议比例)",
    )
    task_completion_resilience: float | None = Field(default=None, description="B10 任务完成韧性")

    # 预留：原始聚合快照
    raw_snapshot: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))


class InterventionTask(SQLModel, table=True):
    """干预任务 — 由 Agent-1/2/3 生成，供教师端查看与执行。"""

    __tablename__ = "intervention_tasks"

    id: int | None = Field(default=None, primary_key=True)
    student_id: int = Field(foreign_key="users.id", index=True)
    class_id: str | None = Field(default=None, max_length=64, index=True)
    agent_type: str = Field(max_length=16)  # bottom | middle | top | manual
    title: str = Field(max_length=256)
    description: str = Field(default="")
    suggestion: dict[str, Any] = Field(default_factory=dict, sa_column=Column(JSON))
    status: str = Field(default="pending", max_length=16)  # pending | active | resolved | dismissed
    priority: str = Field(default="normal", max_length=16)  # low | normal | high | critical
    due_date: _dt.date | None = Field(default=None)
    resolved_at: _dt.datetime | None = Field(default=None)
    created_at: _dt.datetime = Field(default_factory=_dt.datetime.utcnow)


class AnalyticsArtifact(SQLModel, table=True):
    """通用分析产物。

    用于持久化 agent 输出、班级近 N 日分析、周报等文本型证据，
    并作为 RAG 的数据库主存。
    """

    __tablename__ = "analytics_artifacts"
    __table_args__ = (
        UniqueConstraint(
            "artifact_type",
            "scope",
            "class_id",
            "user_id",
            "target_date",
            "window_start",
            "window_end",
            "agent_type",
            name="uq_analytics_artifact_scope_window",
        ),
    )

    id: int | None = Field(default=None, primary_key=True)
    artifact_type: str = Field(index=True, max_length=32)
    scope: str = Field(index=True, max_length=16)  # student | class
    user_id: int | None = Field(default=None, foreign_key="users.id", index=True)
    class_id: str | None = Field(default=None, index=True, max_length=64)
    agent_type: str | None = Field(default=None, index=True, max_length=16)
    target_date: _dt.date | None = Field(default=None, index=True)
    window_start: _dt.date | None = Field(default=None, index=True)
    window_end: _dt.date | None = Field(default=None, index=True)
    title: str = Field(default="", max_length=256)
    content: str = Field(default="")
    evidence: list[dict[str, Any]] = Field(default_factory=list, sa_column=Column(JSON))
    meta_data: dict[str, Any] = Field(default_factory=dict, sa_column=Column("metadata", JSON))
    created_at: _dt.datetime = Field(default_factory=_dt.datetime.utcnow)
    updated_at: _dt.datetime = Field(default_factory=_dt.datetime.utcnow)
